apiVersion: skaffold/v3
kind: Config
manifests:
  rawYaml:
    - ./text_generation/k8s/*
build:
  local:
    push: true
  artifacts:
    - image: diegomunozc/transformers
      context: text_generation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.py"
            dest: .

