apiVersion: v1
kind: Service
metadata:
  name: text-generation
spec:
  selector:
    app: text-generation
  ports:
    - name: text-generation
      protocol: TCP
      port: 4000
      targetPort: 80
